[general]
#import = [
#  #"~/.config/alacritty/base16-dark.toml",
#  "~/.config/alacritty/keybindings.toml",
#  #"alacritty-theme/themes/gruvbox_dark.toml",
#] 
working_directory  = "C:/Users/morty"
live_config_reload = true

[keyboard]
bindings = [
# Ctrl + h sends F13
{ key = "h", mods = "Control", chars = "\u001b[1;2P" },
# Ctrl + j sends F14
{ key = "j", mods = "Control", chars = "\u001b[1;2Q" },
]

#[keyboard]
#bindings = [
#  { key = "J", mods = "Control", action = "ReceiveChar", chars = "\u001b[25~" }
#]

#[keyboard]
# bindings = [{ <key>, <mods>, <mode>, <command> | <chars> | <action> },]
# To unset a default binding, you can use the action "ReceiveChar", 
# to remove it or "None" to inhibit any action.

#bindings = [
#  #{ key = "v", mods = "Control",       mode = "AppCursor", action = "ReceiveChar" },
#  { mods = "Control", key  = "v",        
#    mode = "AppCursor|Appkeypad|Search|Alt|Vi", 
#    action = "None"  
#  },
#
#  { key = "V", mods = "Control|Shift", mode = "AppCursor", action = "Paste"       },
#  { key = "C", mods = "Control|Shift", mode = "AppCursor", action = "Copy"        },
#]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
padding         = { x = 9, y = 7 }
dynamic_padding = true
decorations     = "None"
opacity         = 0.8
dynamic_title   = true
   
[scrolling]
history     = 1000
multiplier  =    3

[font]
normal       = { family = "JetBrainsMono Nerd Font Mono", style = "Regular"     }
bold         = { family = "JetBrainsMono Nerd Font Mono", style = "Bold"        }
italic       = { family = "JetBrainsMono Nerd Font Mono", style = "Italic"      }
bold_italic  = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
# Default:     11.25
size         = 11.25
# Deafult:     { x = 0, y = 0 } 
offset       = { x = 0, y = 0 }
# Deafult:     { x = 0, y = 0 } 
glyph_offset = { x = 1, y = 1 }

[colors.primary]
foreground      = "#8899AA"
background      = "#221100"

[colors.cursor]
text            = "#883333"
cursor          = "#338833"

[colors.vi_mode_cursor]
text            = "#444444"
cursor          = "#777777"

[colors.search]
matches       = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start         = { foreground = "#181818", background = "#f4bf75" }
end           = { foreground = "#181818", background = "#ac4242" }

[cursor]
style            = { shape = "Block", blinking = "On" }
blink_interval   = 750
blink_timeout    = 5
unfocused_hollow = true
thickness        = 0.12

[terminal]
# shell = "<string>" | { program = "<string>", args = ["<string>",] }
shell = "pwsh"
# osc52 = "Disabled" | "OnlyCopy" | "OnlyPaste" | "CopyPaste"
osc52 = "Disabled"
